version: '2'
services:
  node-red:
    build:
      context: .
      dockerfile: /home/cian/Desktop/DT224/FYP/testnode/Dockerfile
    environment:
      - TZ=Europe/Amsterdam
    ports:
      - "1880:1880"
    networks:
      - node-red-net
    volumes:
      - ./data:/data
    restart: always
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.1.6
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: 'TestTopic:1:1'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  mosquitto:
    image: eclipse-mosquitto
    hostname: mosquitto
    container_name: mosquitto
    expose:
      - "1883"
      - "9001"
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - default
  grafana:
      image: grafana/grafana
      container_name: grafana
      restart: always
      ports:
        - 3000:3000
      networks:
        - monitoring
      volumes:
        - grafana-volume:/var/lib/grafana
  influxdb:
      image: influxdb
      container_name: influxdb
      restart: always
      ports:
        - 8086:8086
      networks:
        - monitoring
      volumes:
        - influxdb-volume:/var/lib/influxdb
volumes:
  grafana-volume:
    external: true
  influxdb-volume:
    external: true
  node-red-data:
networks:
  node-red-net:
  monitoring:
